apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-twd0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-twd0
    app.kubernetes.io/part-of: tkrw-pr714-0075-0021-app
  name: devfile-sample-twd0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-twd0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-twd0
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0021-tenant/tkrw-pr714-0075-0021-app/devfile-sample-twd0@sha256:c9a019135f62e5a6569bd9c8a16321e8a4b10fe090103ec332aef040344f84a7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
